<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class bookDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('BookDetail')->insert([
            'bookId'=>1,
            'genreId'=>1
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>1,
            'genreId'=>2
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>1,
            'genreId'=>3
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>1,
            'genreId'=>4
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>2,
            'genreId'=>1
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>2,
            'genreId'=>4
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>2,
            'genreId'=>5
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>3,
            'genreId'=>6
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>3,
            'genreId'=>7
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>4,
            'genreId'=>8
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>4,
            'genreId'=>1
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>4,
            'genreId'=>4
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>4,
            'genreId'=>9
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>5,
            'genreId'=>1
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>5,
            'genreId'=>4
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>5,
            'genreId'=>3
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>5,
            'genreId'=>2
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>6,
            'genreId'=>10
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>6,
            'genreId'=>11
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>6,
            'genreId'=>12
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>7,
            'genreId'=>13
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>7,
            'genreId'=>4
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>7,
            'genreId'=>3
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>8,
            'genreId'=>1
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>8,
            'genreId'=>8
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>8,
            'genreId'=>14
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>9,
            'genreId'=>1
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>9,
            'genreId'=>15
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>9,
            'genreId'=>16
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>10,
            'genreId'=>1
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>10,
            'genreId'=>3
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>10,
            'genreId'=>16
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>11,
            'genreId'=>1
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>11,
            'genreId'=>3
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>11,
            'genreId'=>4
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>11,
            'genreId'=>13
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>12,
            'genreId'=>16
        ]);
        \DB::table('BookDetail')->insert([
            'bookId'=>12,
            'genreId'=>4
        ]);

    }
}
